### ISSUE TITLE
Desenvolver landing page

### ISSUE THREAD

**Issue by juliano-possamai** [EthicAI/ethicai#3]
Criar o front da tela principal do sistema, NÃO É A DO CHAT
podem utilizar textos do lorem ipsum para preencher o layout

Definir os textos que serão usados na landing page, e atualizar o front dela com informações básicas sobre a importância da ética e o funcionamento do sistema

**Comment by otavioP1** [comment]
Revisor: Fernando

**Comment by FernandoGiovanellaDias** [comment]
Na tela do chat, a paleta de cores atual não está alinhada com a da landing page.
**Solicito que entre em contato com o Scrum Master para validar essa questão.**

Por favor, reposicione o tópico "Comece Agora: Faça da Ética um Valor Pessoal e Profissional" como o segundo da página, logo abaixo de "Por que a Ética é Essencial em Nossas Vidas?". Isso permitirá que os usuários que já conhecem e utilizam o chat encontrem esse conteúdo facilmente, sem precisar rolar até o fim da página.

**Comment by WillsSilva** [comment]
Já validei a situação com o Scrum Master e, após análise, decidimos manter a paleta de cores atual, pois ela está alinhada com os objetivos de design e usabilidade estabelecidos para o projeto.

Reposicionei o tópico "Comece Agora: Faça da Ética um Valor Pessoal e Profissional" e fiz a alteração do seu texto.

**Comment by FernandoGiovanellaDias** [comment]
Perfeito, já verifiquei a tela e tudo certo

pode finalizar a tarefa
